# 2.行列積

以下のような行列A、Bを考えます。

\begin{equation*}
  A =
  \begin{bmatrix}
    -1 &  2 &  3 \\
     4 & -5 &  6 \\
     7 &  8 & -9 \\
  \end{bmatrix}
  ,
  B =
  \begin{bmatrix}
    0 & 2 &  1 \\
    0 & 2 & -8 \\
    2 & 9 & -1 \\
  \end{bmatrix}
\end{equation*}


NumPyで表すと次のようになります。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

\begin{align}
  AB &=
  \begin{bmatrix}
    (-1×0) + ( 2×0) + ( 3×2) & (-1×2) + ( 2×2) + ( 3×9) & (-1×1) + ( 2×-8) + ( 3×-1) \\
    ( 4×0) + (-5×0) + ( 6×2) & ( 4×2) + (-5×2) + ( 6×9) & ( 4×1) + (-5×-8) + ( 6×-1) \\
    ( 7×0) + ( 8×0) + (-9×2) & ( 7×2) + ( 8×2) + (-9×9) & ( 7×1) + ( 8×-8) + (-9×-1) \\
  \end{bmatrix}\\
  &= 
  \begin{bmatrix}
    6 & 29 & -20 \\
    12 &  52 &  38 \\
    -18 & -51 &  -48 \\
  \end{bmatrix}\\
\end{align}

上記がgithub上で表示崩れを起こすため下記に同じ内容を記載

\begin{equation*}
  AB =
  \begin{bmatrix}
    (-1×0) + ( 2×0) + ( 3×2) & (-1×2) + ( 2×2) + ( 3×9) & (-1×1) + ( 2×-8) + ( 3×-1) \\
    ( 4×0) + (-5×0) + ( 6×2) & ( 4×2) + (-5×2) + ( 6×9) & ( 4×1) + (-5×-8) + ( 6×-1) \\
    ( 7×0) + ( 8×0) + (-9×2) & ( 7×2) + ( 8×2) + (-9×9) & ( 7×1) + ( 8×-8) + (-9×-1) \\
  \end{bmatrix}\\
\end{equation*}

\begin{equation*}
   =
  \begin{bmatrix}
    6 & 29 & -20 \\
    12 &  52 &  38 \\
    -18 & -51 &  -48 \\
  \end{bmatrix}\\
\end{equation*}


## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

> If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [2]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 3.行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。


## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。



1. 行列Aの(0,0)の要素 $a_{0,0}$ と行列Bの(0,0)の要素 $b_{0,0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0,1}$ と行列Bの(1,0)の要素 $b_{1,0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0,2}$ と行列Bの(2,0)の要素 $b_{2,0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

\begin{equation*}
  \sum_{k=0}^{2}{a_{0,k}}{b_{k,0}}
\end{equation*}

です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [5]:
def my_calc(ndarray_1, ndarray_2):
    answer = np.zeros([ndarray_1.shape[0], ndarray_2.shape[1]])
    for k in range(ndarray_1.shape[0]):
        value = 0
        value += ndarray_1[0, k] * ndarray_2[k, 0]
    answer[0, 0] = value
    return answer

my_calc(a_ndarray, b_ndarray)       

array([[6., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3×3$ の行列Cの各要素 $c_{i,j}$ は数式で表すと次のようになります。

\begin{equation*}
  c_{i,j} =
  \sum_{k=0}^{2}{a_{i,k}}{b_{k,j}}
\end{equation*}

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$を1増やすと、次の行や列に移ることができます。

<img src="./img/1.jpg" style="width:400px;">

In [6]:
def my_calc_2(ndarray_1, ndarray_2):
    answer = np.zeros([ndarray_1.shape[0], ndarray_2.shape[1]])
    for i in range(ndarray_1.shape[1]):
        for j in range(ndarray_2.shape[0]):
            value = 0
            for k in range(ndarray_1.shape[1]):
                value += ndarray_1[i, k] * ndarray_2[k, j]
            answer[i, j] = value
    return answer

my_calc_2(a_ndarray, b_ndarray)      

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 4.行列積が定義されない組み合わせの行列

次に以下のような例を考えます。

\begin{equation*}
  D =
  \begin{bmatrix}
    -1 &  2 & 3 \\
     4 & -5 & 6 \\
  \end{bmatrix}
  ,
  E =
  \begin{bmatrix}
    -9 &  8 & 7 \\
     6 & -5 & 4 \\
  \end{bmatrix}
\end{equation*}

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [8]:
class MatrixCalcError(Exception):
    """行列Aの列・行列Bの行が異なることによるエラー"""
    pass

def my_calc(ndarray_1, ndarray_2):
    try:
        # 行列計算が可能か判定
        if ndarray_1.shape[1] != ndarray_2.shape[0]:
            raise MatrixCalcError
            
        # 行列計算
        answer = np.zeros([ndarray_1.shape[0], ndarray_2.shape[1]])
        for i in range(ndarray_1.shape[1]):
            for j in range(ndarray_2.shape[0]):
                value = 0
                for k in range(ndarray_1.shape[1]):
                    value += ndarray_1[i, k] * ndarray_2[k, j]
                answer[i, j] = value
        return answer
    
    except MatrixCalcError as e:
        print('[ERROR] 行列Aの列・行列Bの行が一致していないため積の計算ができません。')
        print(type(e))

my_calc(d_ndarray, e_ndarray)

[ERROR] 行列Aの列・行列Bの行が一致していないため積の計算ができません。
<class '__main__.MatrixCalcError'>


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [9]:
a_ndarray.transpose()

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])

In [10]:
b_ndarray.T

array([[ 0,  0,  2],
       [ 2,  2,  9],
       [ 1, -8, -1]])